name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Run Gradle Build
      run: |
        chmod +x ./gradlew
        ./gradlew tasks
        ./gradlew assembleDebug
      
    - name: Find APK Files
      run: find . -name "*.apk" -ls
      
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-apk
        path: app/build/outputs/apk/
