name: Build Soma APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build APK
      run: |
        echo "در حال ساخت APK برای سوما..."
        echo "این یک پیام تست است - APK واقعی نیاز به تنظیمات بیشتر دارد"
        mkdir -p app/build/outputs/apk/debug/
        echo "فایل APK آزمایشی سوما" > app/build/outputs/apk/debug/soma-customer-demo.apk
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: soma-customer-apk
        path: app/build/outputs/apk/debug/
        retention-days: 1
